# Generated by Django 2.2.6 on 2020-12-26 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientportal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportapp.Register'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdeposits',
            name='walletfinance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientportal.WalletFinance'),
        ),
        migrations.AddField(
            model_name='userdepositapproval',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveacamount',
            name='liveaccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientportal.LiveAccount'),
        ),
        migrations.AddField(
            model_name='liveacamount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demoaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demoacamount',
            name='demoaccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientportal.DemoAccount'),
        ),
        migrations.AddField(
            model_name='demoacamount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client_commission',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.Register'),
        ),
    ]
