# Generated by Django 2.2.6 on 2021-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientportal', '0002_auto_20201226_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demoaccount',
            name='equity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demoaccount',
            name='group',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='liveaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='liveaccount',
            name='equity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='liveaccount',
            name='group',
            field=models.CharField(default='', max_length=120),
        ),
    ]
