# Generated by Django 2.2.6 on 2021-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientportal', '0003_auto_20210119_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoaccount',
            name='equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demoaccount',
            name='group',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='liveaccount',
            name='equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='liveaccount',
            name='group',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
