# Generated by Django 2.2.6 on 2021-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientportal', '0005_userwallet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='requested_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='A', max_length=1),
        ),
    ]
