# Generated by Django 2.2.6 on 2021-04-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_auto_20210223_1528'),
        ('clientportal', '0006_auto_20210410_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_worth', models.CharField(choices=[('1', '< 10,000'), ('2', '10000-50,000'), ('3', '50,000-1,00,000'), ('4', ' > 100,000')], default='2', max_length=1)),
                ('employement_status', models.CharField(choices=[('1', 'Employee'), ('2', 'Business Person'), ('3', 'Self-Employed'), ('4', 'Student'), ('5', 'Retired Employee'), ('6', 'Unemployed')], default='1', max_length=1)),
                ('annual_income', models.CharField(choices=[('1', '< 10,000'), ('2', '10000-50,000'), ('3', '50,000-1,00,000'), ('4', ' > 100,000')], default='2', max_length=1)),
                ('industry', models.CharField(choices=[('1', 'Financial Services'), ('1', 'Business Administration & Management'), ('1', 'Health care services'), ('1', 'IT'), ('1', 'Other')], default='1', max_length=1)),
                ('anticipated_deposit', models.CharField(choices=[('1', '< 10,000'), ('2', '10000-50,000'), ('3', ' > 50,000')], default='1', max_length=1)),
                ('us_tax_payer', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='2', max_length=1)),
                ('wealth_source', models.CharField(choices=[('1', 'Savings'), ('2', 'Pension'), ('3', 'Family'), ('4', 'Gift'), ('5', 'Salary'), ('6', 'Inheritance'), ('7', 'Others')], default='5', max_length=1)),
                ('trading_experience', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=1)),
                ('education', models.CharField(choices=[('1', 'High School'), ('2', 'Under Graduate'), ('3', 'Graduate'), ('4', 'Others')], default='3', max_length=1)),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportapp.Register')),
            ],
        ),
    ]
