# Generated by Django 2.2.6 on 2021-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client_id',
            field=models.BigIntegerField(default=1001, unique=True),
        ),
    ]
