# Generated by Django 2.2.6 on 2021-02-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210121_1343'),
        ('sportapp', '0003_auto_20210211_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='acc_type',
            field=models.ManyToManyField(to='dashboard.Addaccounttype'),
        ),
    ]
