# Generated by Django 2.2.6 on 2021-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_register_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='acc_limit',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='register',
            name='demo_acc_limit',
            field=models.IntegerField(default=2),
        ),
    ]
