# Generated by Django 2.2.6 on 2021-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_auto_20210223_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='sans',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='sque',
        ),
        migrations.AddField(
            model_name='register',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
