# Generated by Django 2.2.6 on 2021-11-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210121_1343'),
        ('sportapp', '0006_auto_20210501_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mt4trades',
            fields=[
                ('ticket', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.IntegerField()),
                ('symbol', models.CharField(max_length=16)),
                ('digits', models.IntegerField()),
                ('cmd', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('open_time', models.DateTimeField()),
                ('open_price', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('close_time', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('reason', models.IntegerField()),
                ('conv_rate1', models.FloatField()),
                ('conv_rate2', models.FloatField()),
                ('commission', models.FloatField()),
                ('commission_agent', models.FloatField()),
                ('swaps', models.FloatField()),
                ('close_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('taxes', models.FloatField()),
                ('comment', models.CharField(max_length=32)),
                ('internal_id', models.IntegerField()),
                ('margin_rate', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('gw_volume', models.IntegerField()),
                ('gw_open_price', models.IntegerField()),
                ('gw_close_price', models.IntegerField()),
                ('modify_time', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'MT4_TRADES',
            },
        ),
        migrations.CreateModel(
            name='Mt4users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'MT4_USERS',
            },
        ),
        migrations.RenameField(
            model_name='register',
            old_name='ip_address',
            new_name='client_ib',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='language',
            new_name='sans',
        ),
        migrations.AddField(
            model_name='register',
            name='sque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Securityque'),
        ),
        migrations.AddField(
            model_name='registerusercampaign',
            name='mt4_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registerusercampaign',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
