# Generated by Django 2.2.6 on 2021-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_method',
            name='first_deposit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction_method',
            name='first_deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
