# Generated by Django 2.2.6 on 2020-09-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction_ibmethod_mdl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction_IbMethod',
        ),
    ]
