# Generated by Django 2.2.6 on 2020-09-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_transaction_ibmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('enabled_state', models.BooleanField(blank=True, null=True)),
                ('default_state', models.BooleanField(blank=True, null=True)),
                ('country_list', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Agentusercreate')),
                ('sales_queues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SalesQueue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
