# Generated by Django 2.2.6 on 2020-09-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200928_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addsalesnotes',
            old_name='_u',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='addsalesnotes',
            old_name='name',
            new_name='note',
        ),
        migrations.AddField(
            model_name='addsalesnotes',
            name='client_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
