# Generated by Django 2.2.6 on 2021-01-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
        ('dashboard', '0006_auto_20200928_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction_method',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='addsalesnotes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportapp.Register'),
        ),
    ]
